/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_example_pynixs_dodistortion_OpenCVUtils */

#ifndef _Included_com_example_pynixs_dodistortion_OpenCVUtils
#define _Included_com_example_pynixs_dodistortion_OpenCVUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pynixs_dodistortion_OpenCVUtils
 * Method:    getDistortion
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_example_pynixs_dodistortion_OpenCVUtils_getDistortion
  (JNIEnv *, jobject, jobject, jobject);


#ifdef __cplusplus
}
#endif
#endif
